/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextSegment } from "./utils/text-segment";
export namespace Components {
    interface AwesomeTextHighlight {
        "text": string;
        "textSegmentMatchRegExp": RegExp;
    }
}
export interface AwesomeTextHighlightCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAwesomeTextHighlightElement;
}
declare global {
    interface HTMLAwesomeTextHighlightElement extends Components.AwesomeTextHighlight, HTMLStencilElement {
    }
    var HTMLAwesomeTextHighlightElement: {
        prototype: HTMLAwesomeTextHighlightElement;
        new (): HTMLAwesomeTextHighlightElement;
    };
    interface HTMLElementTagNameMap {
        "awesome-text-highlight": HTMLAwesomeTextHighlightElement;
    }
}
declare namespace LocalJSX {
    interface AwesomeTextHighlight {
        "onTextSegmentsGenerated"?: (event: AwesomeTextHighlightCustomEvent<TextSegment[]>) => void;
        "text"?: string;
        "textSegmentMatchRegExp"?: RegExp;
    }
    interface IntrinsicElements {
        "awesome-text-highlight": AwesomeTextHighlight;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awesome-text-highlight": LocalJSX.AwesomeTextHighlight & JSXBase.HTMLAttributes<HTMLAwesomeTextHighlightElement>;
        }
    }
}
